name: Java CI with Maven

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o Java (Java 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Compila o projeto (sem rodar testes)
      - name: Compile with Maven
        run: mvn -B clean compile

      # 4. Executa os testes separadamente
      - name: Run tests with Maven
        run: mvn -B test
